---
version: '3'
services:
    jackson:
        image: boxyhq/jackson
        ports: 
        - 5225:5225
        - 3366:3366
        environment:
        - DB_ENGINE=sql
        - DB_TYPE=postgres
        - DB_URL=postgres://postgres:postgres@postgres:5432/postgres
        - JACKSON_API_SECRET=HelloWorld
        - NEXTAUTH_URL=http://localhost:5225
        - EXTERNAL_URL=http://localhost:5225
        - NEXTAUTH_SECRET=super-secret
        - NEXTAUTH_ADMIN_CREDENTIALS=admin@company.com:secretpassword
        - DO_NOT_TRACK=1
        depends_on:
        - postgres

    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
        - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata: